"""
Report models for report generation and management.
"""
import enum
from datetime import datetime
from typing import Optional, List
from uuid import uuid4

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    JSON,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.db.base import Base


class ReportType(str, enum.Enum):
    """Report types."""
    EXECUTIVE_SUMMARY = "executive_summary"
    INCIDENT_REPORT = "incident_report"
    THREAT_INTELLIGENCE = "threat_intelligence"
    VULNERABILITY_ASSESSMENT = "vulnerability_assessment"
    COMPLIANCE = "compliance"
    DAILY_SOC = "daily_soc"
    WEEKLY_SOC = "weekly_soc"
    MONTHLY_SOC = "monthly_soc"
    CUSTOM = "custom"
    EXPORT = "export"


class ReportStatus(str, enum.Enum):
    """Report generation status."""
    PENDING = "pending"
    GENERATING = "generating"
    COMPLETED = "completed"
    FAILED = "failed"
    EXPIRED = "expired"


class ReportFormat(str, enum.Enum):
    """Report output formats."""
    PDF = "pdf"
    HTML = "html"
    JSON = "json"
    CSV = "csv"
    DOCX = "docx"


class Report(Base):
    """Report model for generated reports."""
    __tablename__ = "reports"
    
    id: Mapped[UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    report_id: Mapped[str] = mapped_column(String(100), unique=True, index=True, nullable=False)
    
    # Report info
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    report_type: Mapped[ReportType] = mapped_column(Enum(ReportType), nullable=False, index=True)
    format: Mapped[ReportFormat] = mapped_column(Enum(ReportFormat), default=ReportFormat.PDF, nullable=False)
    
    # Status
    status: Mapped[ReportStatus] = mapped_column(Enum(ReportStatus), default=ReportStatus.PENDING, nullable=False, index=True)
    progress: Mapped[int] = mapped_column(Integer, default=0, nullable=False)  # 0-100
    
    # Generated by
    generated_by_id: Mapped[Optional[UUID]] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    generated_by_name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    
    # Scheduling
    is_scheduled: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    schedule_cron: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    schedule_timezone: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    next_run: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    last_run: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    
    # Recipients
    recipients: Mapped[Optional[List[str]]] = mapped_column(JSON, nullable=True)  # Email addresses
    notification_channels: Mapped[Optional[List[str]]] = mapped_column(JSON, nullable=True)  # email, slack, teams
    
    # Content
    template_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    parameters: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)  # Report parameters/filters
    sections: Mapped[Optional[List[dict]]] = mapped_column(JSON, nullable=True)  # Report sections config
    
    # Output
    file_path: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    file_size: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    file_hash: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)  # SHA256
    download_url: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    download_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    expires_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True, index=True)
    
    # Error handling
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    error_details: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    retry_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    
    # Timing
    started_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    duration_seconds: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow, nullable=False, index=True)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    generated_by: Mapped[Optional["User"]] = relationship("User", lazy="selectin")
    
    __table_args__ = (
        Index("ix_reports_type_status", "report_type", "status"),
        Index("ix_reports_generated_by_time", "generated_by_id", "created_at"),
        Index("ix_reports_scheduled_next", "is_scheduled", "next_run"),
        Index("ix_reports_expires", "expires_at"),
    )
    
    def __repr__(self) -> str:
        return f"<Report(id={self.id}, report_id={self.report_id}, title={self.title}, type={self.report_type.value}, status={self.status.value})>"


class ReportTemplate(Base):
    """Report templates for reusable report configurations."""
    __tablename__ = "report_templates"
    
    id: Mapped[UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    template_id: Mapped[str] = mapped_column(String(100), unique=True, index=True, nullable=False)
    
    # Template info
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    report_type: Mapped[ReportType] = mapped_column(Enum(ReportType), nullable=False)
    
    # Template content
    template_config: Mapped[dict] = mapped_column(JSON, nullable=False)  # Jinja2 template or section config
    default_parameters: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    default_format: Mapped[ReportFormat] = mapped_column(Enum(ReportFormat), default=ReportFormat.PDF, nullable=False)
    
    # Sections
    sections: Mapped[List[dict]] = mapped_column(JSON, nullable=False)  # Ordered list of section configs
    
    # Metadata
    is_system: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    
    # Ownership
    created_by_id: Mapped[Optional[UUID]] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    created_by: Mapped[Optional["User"]] = relationship("User", lazy="selectin")
    
    def __repr__(self) -> str:
        return f"<ReportTemplate(id={self.id}, template_id={self.template_id}, name={self.name})>"


class ReportSchedule(Base):
    """Scheduled report configurations."""
    __tablename__ = "report_schedules"
    
    id: Mapped[UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    schedule_id: Mapped[str] = mapped_column(String(100), unique=True, index=True, nullable=False)
    
    # Schedule info
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Template reference
    template_id: Mapped[UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("report_templates.id"), nullable=False)
    
    # Schedule
    cron_expression: Mapped[str] = mapped_column(String(100), nullable=False)
    timezone: Mapped[str] = mapped_column(String(50), default="UTC", nullable=False)
    
    # Recipients
    recipients: Mapped[List[str]] = mapped_column(JSON, nullable=False)
    notification_channels: Mapped[List[str]] = mapped_column(JSON, nullable=False)
    
    # Parameters
    parameters: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    format: Mapped[ReportFormat] = mapped_column(Enum(ReportFormat), default=ReportFormat.PDF, nullable=False)
    
    # Status
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    last_run: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    next_run: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True, index=True)
    run_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    failure_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    last_error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # Ownership
    created_by_id: Mapped[Optional[UUID]] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    
    # Relationships
    template: Mapped["ReportTemplate"] = relationship("ReportTemplate", lazy="selectin")
    created_by: Mapped[Optional["User"]] = relationship("User", lazy="selectin")
    
    def __repr__(self) -> str:
        return f"<ReportSchedule(id={self.id}, schedule_id={self.schedule_id}, name={self.name}, active={self.is_active})>"