"""Test password verification compatibility."""
import sys
sys.path.insert(0, r"C:\Users\abhishek\Downloads\ai-based soc\backend")
from backend.core.security import hash_password, verify_password

# Generate a new hash with the current code
new_hash = hash_password("Admin@123")
print("New hash generated by current code:")
print("Full:", new_hash)
print()

# Test verification with the new hash
result1 = verify_password("Admin@123", new_hash)
print(f"verify_password('Admin@123', new_hash): {result1}")

result2 = verify_password("WrongPassword", new_hash)
print(f"verify_password('WrongPassword', new_hash): {result2}")
print()

# Check hash format
print("Hash format check:")
print("  starts with $pbkdf2-sha256$: ", new_hash.startswith("$pbkdf2-sha256$"))
print("  contains 29000: ", "29000" in new_hash)